version: '3.8'
services:
db:
build: docker/psql
restart: always
ports:
- "5432:5432"
environment:
DJANGO_DB_USER: ${POSTGRES_USER}
DJANGO_DB_PASSWORD: ${POSTGRES_PASSWORD}
DJANGO_DB_HOST: ${POSTGRES_HOST}
DJANGO_DB_PORT: ${POSTGRES_PORT}

web:
build: .
restart: always
ports:
- "80:80"
depends_on:
- db
environment:
DJANGO_DB_USER: ${POSTGRES_USER}
DJANGO_DB_PASSWORD: ${POSTGRES_PASSWORD}
DJANGO_DB_HOST: ${POSTGRES_HOST}
DJANGO_DB_PORT: ${POSTGRES_PORT}
- DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
- DJANGO_DEBUG: ${DJANGO_DEBUG}
- ALLOWED_HOSTS: ${ALLOWED_HOSTS}
-AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
-AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
-AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}

